### 
POST http://localhost:9000/api/products HTTP/1.1
Content-Type: application/json

{
  "name": "Running Shoes blue",
  "description": "Shoes for play your best sports as a professional player",
  "price": 89.99,
  "brand": null,
  "target": ["Kids", "Teenagers"],
  "sport": ["Football", "Volleyball", "BasketBall"],
  "size": ["S", "M", "L"],
  "colorInformation": [
    {"color": "Red", "imagePath": "https://res.cloudinary.com/tenis1red.jpg"},
    {"color": "Yellow", "imagePath": "https://res.cloudinary.com/tenis1Yellow.jpg"}],
  "imagePath": ["https://res.cloudinary.com/scrubsandbeyond/image/upload/q_auto:best/fly_black-cloudysky.jpg"],
  "inStock": [[10, 24], [12, 3], [13, 54]]
}

### 
GET http://localhost:9000/api/products HTTP/1.1 


###
GET http://localhost:9000/api/products/654afdd0b4d98a9ceee66565 HTTP/1.1


### 
PUT http://localhost:9000/api/products/654afdd0b4d98a9ceee66565 HTTP/1.1
Content-Type: application/json

{
  "name": "Running Shoes blue",
  "description": "Shoes for play your best sports as a professional player",
  "price": 89.99,
  "brand": null,
  "target": ["Man", "Woman"],
  "sport": ["Football"],
  "size": ["S", "M", "L"],
  "colorInformation": [
    {"color": "Red", "imagePath": "https://res.cloudinary.com/tenis1red.jpg"},
    {"color": "Yellow", "imagePath": "https://res.cloudinary.com/tenis1Yellow.jpg"}],
  "imagePath": ["https://res.cloudinary.com/scrubsandbeyond/image/upload/q_auto:best/fly_black-cloudysky.jpg"],
  "inStock": [[10, 24], [12, 3], [13, 54]]
}

### 
DELETE http://localhost:9000/api/products/654afdd0b4d98a9ceee66565 HTTP/1.1
