###
POST https://backend-fullapirest.onrender.com/api/brands HTTP/1.1
Content-Type: application/json

{
  "name": "Nike",
  "imagePath": "https://i.postimg.cc/SKJwcWjX/Nike.png"
}

###
POST https://backend-fullapirest.onrender.com/api/brands HTTP/1.1
Content-Type: application/json

{
"name": "Adidas",
"imagePath": "https://i.postimg.cc/90d3rC0J/Adidas.png"
}

###
GET https://backend-fullapirest.onrender.com/api/brands HTTP/1.1

###
PUT https://backend-fullapirest.onrender.com/api/brands/654b90cfb4182ff7f5a419fa HTTP/1.1
Content-Type: application/json

{
  "name": "Nike",
  "imagePath": "https://i.postimg.cc/SKJwcWjX/Nike.png"
}

###
DELETE https://backend-fullapirest.onrender.com/api/brands/654b9143b4182ff7f5a41a04 HTTP/1.1