### 
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "firstName": "Maria",
  "lastName": "Galindo",
  "address": "Calle los molinos, Cochabamba, Sacaba",
  "email": "maria@gmail.com",
  "creditCard": {
    "creditCardNumber": 153264578683,
    "expirationDate": "2028-04-01",
    "cvc": 753,
    "cardType": "Debit Card"
  }
}

### 
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json 

{
  "firstName": "Juan",
  "lastName": "Pa",
  "address": "Chuquisaca, Bolivia",
  "email": "Juan@gmail.com",
  "creditCard": {
    "creditCardNumber": 168305321421,
    "expirationDate": "2025-04-01",
    "cvc": 123,
    "cardType": "PayPal"
  }
}

### 
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json 

{
  "firstName": "Tyrone",
  "lastName": "Gonzales",
  "address": "Caracas, Venezuela",
  "email": "can@gmail.com",
  "creditCard": {
    "creditCardNumber": 253231244424,
    "expirationDate": "2023-12-01",
    "cvc": 696,
    "cardType": "Credit Card"
  }
}

### 
GET http://localhost:9000/api/users HTTP/1.1 


###
GET http://localhost:9000/api/users/654aff711988ebedb79f48c4 HTTP/1.1


### 
PUT http://localhost:9000/api/users/654aff711988ebedb79f48c4 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Maria",
  "lastName": "Galindo",
  "address": "Cochabamba, Sacaba",
  "email": "MariaLaGalindo@gmail.com",
  "creditCard": {
    "creditCardNumber": 153264578683,
    "expirationDate": "2025-04-01",
    "cvc": 752,
    "cardType": "Debit Card"
  }
}

### 
DELETE http://localhost:9000/api/users/654b00f91988ebedb79f48ce HTTP/1.1
