### 
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json 

{
    "name": "Maria",
    "age": 33,
    "email": "Maria@gmail.com"
}

### 
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json 

{
    "name": "Miranda",
    "age": 18,
    "email": "Miranda.Pe.aaaa@gmail.com"
}

### 
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json 

{
    "name": "Pedro",
    "age": 32,
    "email": "PedroTu@gmail.com"
}

### 
GET http://localhost:9000/api/users HTTP/1.1 


###
GET http://localhost:9000/api/users/6549b191a492f8177bb94e5d HTTP/1.1 


### 
PUT http://localhost:9000/api/users/6549b191a492f8177bb94e5d HTTP/1.1
Content-Type: application/json

{
    "name": "Maria Miranda",
    "age": 33,
    "email": "MariaMls@gmail.com"
}

### 
DELETE http://localhost:9000/api/users/6540990ca81626c8078467e3 HTTP/1.1 
